### ISSUE TITLE
Allow French keyboard 'alt' input in CoCalc online terminal under macOS

### ISSUE THREAD

**Issue by slel** [sagemathinc/cocalc#2221]
Using a French keyboard under macOS, some characters require 'alt' to input them.
Those include `~`, `|`, `{`, `}`, `[`, `]`, `…`, `•`, `€`.

Not all browsers let me input them in CoCalc's online terminal:
- working
  - Firefox 54.0.1
- failing
  - Opera 46.0.2597.57
  - Chrome 59.0.3071.115
  - Safari 10.1.2

The tool at https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html
reveals e.g. that when I type `alt-shift-L`, the failing browsers send `alt+|`
instead of `|`, while Firefox 54.0.1 just sends `|` as it should.

**Comment by slel** [comment]
Output from the key-event-test page cited above (in Opera):

Event type | charCode | keyCode | which | shift | ctrl | alt | meta | key | code | location | repeat | data | locale | Input field
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
keyup | 0 | 18 | 18 | ✗ | ✗ | ✗ | ✗ | 'Alt' | AltLeft | LEFT | false | - | - | '\|'
keyup | 0 | 16 | 16 | ✗ | ✗ | ✓ | ✗ | 'Shift' | ShiftLeft | LEFT | false | - | - | '\|'
keyup | 0 | 220 | 220 | ✓ | ✗ | ✓ | ✗ | '\|' | KeyL | 0 | false | - | - | '\|'
input | - | - | - | ✗ | ✗ | ✗ | ✗ | - | - | - | - | - | - | '\|'
textInput | - | - | - | ✗ | ✗ | ✗ | ✗ | - | - | - | - | '\|' | - | ''
keypress | 124 '\|' | 124 '\|' | 124 '\|' | ✓ | ✗ | ✓ | ✗ | '\|' | KeyL | 0 | false | - | - | ''
keydown | 0 | 220 | 220 | ✓ | ✗ | ✓ | ✗ | '\|' | KeyL | 0 | false | - | - | ''
keydown | 0 | 16 | 16 | ✓ | ✗ | ✓ | ✗ | 'Shift' | ShiftLeft | LEFT | false | - | - | ''
keydown | 0 | 18 | 18 | ✗ | ✗ | ✓ | ✗ | 'Alt' | AltLeft | LEFT | false | - | - | ''

**Comment by williamstein** [comment]
I’m closing this because I think Gonzalo Tornaria  completely fixed such problems (he wanted to make the terminal work for non-US users).  Please re-open if this is not all fixed now.

**Comment by slel** [comment]
Gonzalo Tornaría's fix was for #2211 and does not fix the issue here.

Typing alt-L, alt-(, alt-), alt-shift-(, alt-shift-), alt-., alt-shift-.,
still won't produce the expected `|`, `{`, `}`, `[`, `]`, `…`, `•` using
a French Mac keyboard.

Note however that on a French Mac keyboard, the case of the character `~`,
which combines #2211 and the issue here as it both requires 'alt' (alt-N)
and acts as a dead key, is miraculously fixed by the fix for #2211:
one can now type alt-N followed by space and get `~`.

Regarding the still standing bug, as indicated in the first two comments
on this issue, the browsers are guilty here, they should really be fixed.
I am not sure know where to report the bug to make that happen, though.

In the meanwhile, a fix in CoCalc would be nice.

As noted at https://github.com/sagemathinc/cocalc/issues/2211#issue-244168326

> CoCalc's online terminal is currently based on [term.js](https://github.com/chjj/term.js/)
> whose README file has this warning:
>
> > **This project is no longer maintained.**
> > **For a maintained fork take a look at [sourcelair/xterm.js](https://github.com/sourcelair/xterm.js).**
>
> The website https://xtermjs.org points to https://www.sourcelair.com
> where one can get a 30-day free trial. The terminal there lets one input
> `~` in a French keyboard by typing `~` followed by spacebar, as expected.
>
> So it might be worth considering replacing the use of term.js by that of xterm.js.

I understand that CoCalc actually uses a rewrite of the original term.js
and that switching to xterm.js might be a lot of work. But xterm.js works
and is maintained. It is also the terminal used in JupyterLab.

**Comment by slel** [comment]
As a complement to my previous comment: Gonzalo's fix for #2211
actually provides a workaround for users of French Mac keyboards.

As noted, typing alt-N followed by a space now results in `~`,
and alt-N followed by a or n or o now results in `ã`, `ñ`, `õ`,
as expected, but in addition alt-N followed by a character that
normally can't get a tilda results in `~` plus that character,
for instance alt-N followed by b results in `~b` (which is also
the standard behaviour one would expect).

The surprise is now that while shift-alt-L still won't produce `|`,
typing alt-N followed by shift-alt-L now does gives `~|`.

So the workaround with a French Mac keyboard is as follows.

To obtain `|`, `{`, `}`, `[`, `]`, `…`, `•`, etc, one would normally type
alt-L, alt-(, alt-), alt-shift-(, alt-shift-), alt-., alt-shift-., etc.

The workaround is to type alt-N followed by these alt-stuff, and get
`~|`, `~{`, `~}`, `~[`, `~]`, `~…`, `~•`, etc; then delete the `~`.

Much less annoying than typing the desired characters somewhere else
(eg browser's url bar, or other tab in the browser, or other app
such as a text editor) and copy-pasting it to the CoCalc terminal.

This workaround makes life much better, but let's leave the issue open
until it is properly fixed (either in the browsers or in CoCalc).

**Comment by williamstein** [comment]
Specifically, what happens with pari in a terminal (from @slel )
```
There are several ways to run the PARI/GP console in CoCalc.

(a) One can run

        $ gp

    which gives the quite outdated PARI 2.7.5.

(b) One can run

        $ sage -gp

    which gives the recent snapshot of the master branch
    of PARI 2.10.0 that is shipped with Sage.

(c) One can launch Sage in a terminal, and in the Sage REPL
    one can run

        sage: gp.console()

    which also gives the recent snapshot of the master branch
    of PARI 2.10.0 that is shipped with Sage.

In all cases, the PARI banner that we get when starting
the gp console tells the user to type \q to quit.

Emmanuel noticed that in cases (a) and (b), entering \ (backslash)
does not work for him (macOS 10.13.2, French localization,
French keyboard, various browsers: Firefox, Safari).

As you remember, similar issues were encountered before. On the
corresponding CoCalc ticket, I indicated a "workaround", consisting
in typing alt-N (for dead key tilda) followed by backslash, which
results in ~\, and then remove the backslash. See the comment at:
https://github.com/sagemathinc/cocalc/issues/2221#issuecomment-327627844

This workaround works in case (c) but not in cases (a) and (b) above.
This might have to do with (c) using a different version of readline
(or something other than readline) compared to (a) and (b).

I'll try to check what happens with other operating systems.

One thing that might help a little bit is to modify the PARI/GP banner
to indicate that one can type either "\q" or "quit" to end the session.

Best,
Samuel
```

**Comment by slel** [comment]
Actually, I can't get the workaround to work in case (c) either.

I forgot one case in my enumeration above

    (d) Use PARI in a Jupyter notebook worksheet.
        There we can input \ and | with no problem.

**Comment by haraldschilly** [comment]
One user reports for spanish keyboard layouts a similar issue:

* problematic: chrome/windows
* works fine: firefox/windows

**Comment by haraldschilly** [comment]
another user reports issues with

> Google Chrome on Android 5, via a Bluetooth Keyboard.

**Comment by williamstein** [comment]
We switched to xterm.js, which presumably fixes all these issues...

NOTE: we haven't switched on *mobile* yet, e.g., Android, but will soon.  You can use mobile xerm.js to test by making a file ending in .term2.
