### ISSUE TITLE
Accessing project via direct URL doesn't launch it

### ISSUE THREAD

**Issue by navoshta** [sagemathinc/cocalc#3817]
This functionality is specific to Juno client app integrated with CoCalc. Currently the workflow is:

1. User logs in with CoCalc's API page, which returns an API token and sets necessary cookies. The auth URL is as follows:

```
https://cocalc.com/app?get_api_key=juno
```

2. Juno uses CoCalc API to retrieve projects' IDs.
3. When user opens a project, Juno loads project's direct URL in the following format 

```
https://cocalc.com/{project_id}/port/jupyter/
```

4. Since auth cookies are set at step 1 (which could be days/weeks ago from steps 2-4), this should launch the project.

A few days ago I started getting reports from users that CoCalc projects won't start in Juno. I managed to reproduce this, and the pattern seems to be: **projects launch on step 4 only a few hours after you log in**. After some time (I'm still yet to figure out how long it takes exactly, but something around 12 hours), projects accessed via direct URL no longer start up. If you refresh the cookie, i.e. log out and log in again, projects start launching again for the next ~12 hours or so.

Due to a nature of this ticket it's fairly complicated to debug further, as I need to wait for a while to get to this broken state. I will update this ticket with more details if I manage to debug further.

**Comment by williamstein** [comment]
My first guess is that you need to touch the project now using this endpoint: https://doc.cocalc.com/api/touch_project.html

Can you do that via the api?  I think directly querying `https://cocalc.com/{project_id}/port/jupyter/` no longer automatically starts the project, possibly to reduce accidental resource usage of our cluster.

**Comment by navoshta** [comment]
Yep, Juno does call this API every once in a while when the project is already running. I wasn't aware that it needs to be called in order to start it, too. 

Thanks for the tip — I will check if it works and post an update here. If this is indeed the issue, any chance this change can be temporarily reverted? Updating an app can take a while with the App Store review process.

**Comment by williamstein** [comment]
> If this is indeed the issue, any chance this change can be temporarily reverted?

Yes, definitely.     Even permanently.  I think the change might be somewhat accidental as a side effect of other things related to the recent revamp of realtime sync.  I hope to have time to work on this soon (still dealing with abuse fallout right now).

**Comment by williamstein** [comment]
I haven't figured this out yet. Though this

https://github.com/sagemathinc/cocalc/commit/5f87e835a6d0da6302d9793657da8a51a01c63de

might be relevant.  It's relatively recent and could be causing trouble.  Not sure.

**Comment by navoshta** [comment]
Thanks — I'm still trying a few things, but the project seemed to start when I tried accessing it in similar conditions on desktop (i.e. using direct project URL after waiting 12+ hours after last login). Although I did also access the main desktop website, not _just_ the login page, as it happens in Juno. So perhaps it's crucial that the login happens specifically via this URL:

```
https://cocalc.com/app?get_api_key=juno
```

In other words, without accessing the main website. Perhaps it sets cookies differently? I will run a few more tests and update this ticket.

**Comment by williamstein** [comment]
> Yep, Juno does call this API every once in a while when the project is already running. I wasn't aware that it needs to be called in order to start it, too.

I can definitely confirm that touching a project will start it (I tested this and also read the code), and Juno should definitely be doing this first to start the project, and this should completely fix the problem... though it requires an app store update.  

I now very much doubt #5f87e83 is relevant.    The 12-hour cookie stuff is for signing in a user via the auth_token, but you're not using that functionality as far as I can tell (that's what's described here: https://doc.cocalc.com/api/user_auth.html).

It's definitely the case that just doing a GET request on a stopped project (e.g., `https://cocalc.com/{project_id}/port/jupyter/`) does NOT start it running anymore.  I can replicate this (without having to wait any length of time, and straight from a desktop browser) by stopping a project and refreshing that URL, and seeing that the project doesn't start running.  There were various cases in the code where random things were pinging such URL's and waking projects, which was wasting a lot of resources, unfortunately, and it ended up getting disabled.

I agree that it makes sense for getting 
```
https://cocalc.com/{project_id}/port/jupyter/
```
to wake the project, and will prioritize making a change so this is the case (but just for this case).

**Comment by williamstein** [comment]
OK, after looking at this more, I think the problem was a stale cache in some cases, which isn't anything I thought above.  It should now be fixed (via [this commit](https://github.com/sagemathinc/cocalc/commit/cb6bff7a361f6e6b907d4acc577a0e3c1066b0bf)), which is now live.

**Comment by navoshta** [comment]
Thanks for looking into this @williamstein. Weirdly, this doesn't seem to fix the issue for Juno, neither does calling `touch_project` endpoint first as suggested. Very puzzled at this point, I inspected further, and it seems like the authentication cookie actually went missing!

These are the only CoCalc cookies that are available in the storage when I try to access the project in Juno: `__cfduid`, `_ga` and `SMCSERVERID3`. This is odd because Juno doesn't clean up the cookies, or rather when it does, it just wipes out _all_ cookies for CoCalc domain.

Is there any circumstance where CoCalc removes auth cookie(-s)? Could it happen during one of API calls?

**Comment by williamstein** [comment]
Here's a picture showing the remember_me cookie get set after you sign in via `https://cocalc.com/app?get_api_key=juno`, with a very long expire:

![Screenshot 2019-05-14 at 10 01 30 AM](https://user-images.githubusercontent.com/1276278/57717128-5f8b0e80-762f-11e9-88fc-5451a8d70a38.png)

If a user were to explicitly sign out anywhere, that does not delete their cookie (though it does make it invalid).  Same with "Sign Out Everywhere", it makes all cookies invalid but they are still there.

As far as I can tell (and remember) the only cookie cocalc explicitly deletes ever is the get_api_key.

1. What's the cookie situation initially as Juno signs in?  What's the expiration time on remember_me?
2. Can you at least change Juno to check whether or not the user is signed in, and if not, redirect the user to sign in again?   No matter what, you'll need to do that, since a user might click "Sign out everywhere" from the browser.

**Comment by DrXyzzy** [comment]
I tested Juno just now on an iPad Pro. Here's what happens:

## case 1 - works ok if I open a running project first
1. If Juno is running, start a new test run by stopping Juno: hit Home button twice, then swipe Juno app up to stop it.
1. Open Juno Servers list and choose COCALC.
1. Get a list of projects.
1. Choose a running project. It opens and I can use it.
1. Go back to COCALC project list and choose a stopped project. It eventually opens and I can use it.

## case 2 - problem if I try to open a stopped project first
1. Start a new test run by stopping Juno: hit Home button twice, then swipe Juno app up to stop it.
1. Open Juno Servers list and choose COCALC.
1. Get a list of projects.
1. Choose a *stopped* project. Juno goes through about 5 iterations of trying to connect, then bounces me back to the CoCalc API Key Access sign-in screen shown below. At this point, I can't use Juno with CoCalc until I sign in again.

![juno-sign-in](https://user-images.githubusercontent.com/528072/57721393-ac7bde80-7649-11e9-99df-795a3dde26da.png)

**Comment by williamstein** [comment]
I disagree with reopening "Accessing project via direct URL doesn't launch
it" because that problem (which did exist) should now be completely fixed.
 Or am I wrong?

Open a new ticket with a title that describes that actual problem?

**Comment by DrXyzzy** [comment]
Ok. New ticket #3826.
